montanha/api/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2016, Marcelo Jorge Vieira <metal@alucinados.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from tastypie.api import Api

from montanha.api.resources import (
    SupplierResource, SupplierActivityResource, JuridicalNatureResource,
    PoliticalPartyResource, LegislatorResource, InstitutionResource,
    AlternativeLegislatorNameResource, LegislatureResource, MandateResource,
    ExpenseNatureResource, ExpenseResource, PerNatureResource,
    PerNatureByYearResource, PerNatureByMonthResource, PerLegislatorResource,
    BiggestSupplierForYearResource
)


api = Api(api_name='v0')
api.register(SupplierResource(), canonical=True)
api.register(SupplierActivityResource(), canonical=True)
api.register(JuridicalNatureResource(), canonical=True)
api.register(PoliticalPartyResource(), canonical=True)
api.register(LegislatorResource(), canonical=True)
api.register(AlternativeLegislatorNameResource(), canonical=True)
api.register(InstitutionResource(), canonical=True)
api.register(LegislatureResource(), canonical=True)
api.register(MandateResource(), canonical=True)
api.register(ExpenseNatureResource(), canonical=True)
api.register(ExpenseResource(), canonical=True)
api.register(PerNatureResource(), canonical=True)
api.register(PerNatureByYearResource(), canonical=True)
api.register(PerNatureByMonthResource(), canonical=True)
api.register(PerLegislatorResource(), canonical=True)
api.register(BiggestSupplierForYearResource(), canonical=True)


urlpatterns = api.urls

montanha/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (©) 2013 Marcelo Jorge Vieira <metal@alucinados.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView

from montanha.views import (
    query_all, query_biggest_suppliers, query_supplier_all,
    query_legislator_all, show_all, show_per_nature, show_per_legislator,
    show_per_party, show_per_supplier, show_supplier_overview,
    show_legislator_detail, show_supplier_detail, what_is_expenses,
    contact_us, show_index,
)


urlpatterns = [
    # JSON queries
    url(r'^([^/]+)?/?q/all/?$', query_all, name='query-all'),
    url(r'^([^/]+)?/?q/biggest_suppliers/?$', query_biggest_suppliers, name='query-biggest-suppliers'),
    url(r'^([^/]+)?/?q/supplier_all/?$', query_supplier_all, name='query-supplier-all'),
    url(r'^([^/]+)?/?q/legislator_all/?$', query_legislator_all, name='query-legislator-all'),

    url(r'^([^/]+)?/?all/?([^/]+)?/$', show_all, name='show-all'),

    url(r'^([^/]+)?/?per-nature/?([^/]+)?/$', show_per_nature, name='per-nature'),
    url(r'^([^/]+)?/?per-legislator/?([^/]+)?/$', show_per_legislator, name='per-legislator'),
    url(r'^([^/]+)?/?per-party/?([^/]+)?/$', show_per_party, name='per-party'),
    url(r'^([^/]+)?/?per-supplier/?([^/]+)?/$', show_per_supplier, name='per-supplier'),

    url(r'^detail-supplier/(\d+)/?$', show_supplier_overview, name='show-supplier-overview'),

    url(r'^([^/]+)?/?detail-legislator/(\d+)/?$', show_legislator_detail, name='show-legislator-detail'),
    url(r'^([^/]+)?/?detail-supplier/(\d+)/?$', show_supplier_detail, name='show-supplier-detail'),

    # favicon
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('favicon.ico'),
            permanent=True),
        name='favicon'
    ),

    # Robots.txt
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain')),

    # What is expenses?
    url(r'^o-que-e-verba-indenizatoria/?$', what_is_expenses, name='what-is-expenses'),

    # Contact us
    url(r'^fale-conosco/?$', contact_us, name='contact-us'),

    # Index
    url(r'^([^/]+)?/?$', show_index, name='index'),
]

olhoneles/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (©) 2010-2013 Gustavo Noronha Silva
# Copyright (©) 2013 Marcelo Jorge Vieira <metal@alucinados.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from montanha.api import __version__


admin.autodiscover()


urlpatterns = [
    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # API
    url(r'api/v0/',
        include('tastypie_swagger.urls', namespace='olhoneles-v0'),
        kwargs={
            'namespace': 'olhoneles-v0',
            'tastypie_api_module': 'montanha.api.urls.api',
            'version': __version__,
        }),
    url(r'^api/', include('montanha.api.urls')),

    # Montanha
    url(r'^', include('montanha.urls',
                      namespace='montanha',
                      app_name='montanha')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler500 = 'montanha.views.error_500'
handler404 = 'montanha.views.error_404'

montanha/views.py
# -*- coding: utf-8 -*-
#
# Copyright (©) 2013 Marcelo Jorge Vieira <metal@alucinados.com>
# Copyright (©) 2013 Gustavo Noronha Silva <gustavo@noronha.eti.br>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import locale
from datetime import date
from colorsys import hsv_to_rgb

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render as original_render
from django.db.models import Sum, Q
from django.http import HttpResponse, Http404
from django.core.mail import send_mail
from django.conf import settings
from djqscsv import render_to_csv_response
from slugify import slugify

from montanha.models import (
    Expense, Institution, PerNature, PerNatureByYear, ExpenseNature,
    PerNatureByMonth, PerLegislator, Legislator, PoliticalParty, Mandate,
    Supplier, BiggestSupplierForYear, Legislature
)
from montanha.forms import ContactUsForm
from montanha.util import (
    filter_for_institution, get_date_ranges_from_data, ensure_years_in_range
)


locale.setlocale(locale.LC_MONETARY, "pt_BR.UTF-8")
locale.setlocale(locale.LC_TIME, "pt_BR.UTF-8")


def generate_colors(n=7, sat=1.0, val=1.0):
    '''Generates an array of n colors from red to violet, considering
    saturation sat and value val'''
    return ['#%02X%02X%02X' % t for t in [tuple([int(round(c * 255)) for c in t]) for t in [hsv_to_rgb(x / float(n), sat, val) for x in xrange(0, n)]]]


def new_render(request, filter_spec, template, context):
    context['institution'] = None
    context['legislature'] = None
    context['filter_spec'] = None
    context['request'] = request
    if filter_spec:
        institution, legislature = parse_filter(filter_spec)
        context['institution'] = institution
        context['legislature'] = legislature
        context['filter_spec'] = filter_spec
    return original_render(request, template, context)


def get_basic_objects_for_model(filter_spec, model=Expense):
    data = model.objects.all()

    if not filter_spec:
        date_ranges = get_date_ranges_from_data(None, data)
        return data, date_ranges

    institution, legislature = parse_filter(filter_spec)
    if institution:
        data = filter_for_institution(data, institution)

    if legislature:
        data = data.filter(mandate__legislature=legislature)

    date_ranges = get_date_ranges_from_data(institution, data)

    return data, date_ranges


def parse_filter(filter_spec):
    if not filter_spec:
        return None, None

    parts = filter_spec.split(':', 1)

    try:
        institution = Institution.objects.get(siglum=parts[0])
    except Institution.DoesNotExist:
        return None, None

    if len(parts) == 1:
        return institution, None

    try:
        legislature = institution.legislature_set.get(date_start__year=parts[1])
    except (ValueError, Legislature.DoesNotExist):
        raise Http404

    return institution, legislature


def show_index(request, filter_spec):

    c = {}

    if filter_spec:
        institution, _ = parse_filter(filter_spec)
        if not institution:
            raise Http404
        legislatures = institution.legislature_set.order_by('-date_start').all()
        c['legislatures'] = [l for l in legislatures
                             if Expense.objects.filter(mandate__legislature=l).count()]
        c['img'] = institution.siglum.lower() + '.png'
        return new_render(request, filter_spec, 'institution.html', c)

    return new_render(request, filter_spec, 'index.html', c)


def show_robots_txt(request):
    return HttpResponse('User-Agent: *\nAllow: /\n')


def error_500(request):
    c = {}
    return original_render(request, '500.html', c)


def error_404(request):
    c = {}
    return original_render(request, '404.html', c)


def _export_csv(request, data, field_header_map={}):
    filename = slugify(request.path).replace('-csv', '.csv')
    return render_to_csv_response(
        data, filename=filename, field_header_map=field_header_map
    )


def show_per_nature(request, filter_spec, export_format=''):

    institution, legislature = parse_filter(filter_spec)
    data = PerNature.objects.filter(institution=institution, legislature=legislature)

    if export_format:
        data = data.values(
            'institution__siglum',
            'legislature__date_start',
            'legislature__date_end',
            'nature__name',
            'expensed',
        )
        field_header_map = {
            'institution__siglum': u'Instituição',
            'legislature__date_start': u'Início da legislatura',
            'legislature__date_end': u'Fim da legislatura',
            'nature__name': u'Tipo de gasto',
            'expensed': u'Valor',
        }
        return _export_csv(request, data, field_header_map)

    date_ranges = get_date_ranges_from_data(institution, data, consolidated_data=True)

    if legislature:
        start_year = legislature.date_start.year
        end_year = legislature.date_end.year
    else:
        start_year = date_ranges['cdf'].year
        end_year = date_ranges['cdt'].year

    time_series = []
    for d in data:
        aux = []
        cummulative = .0
        time_series.append(dict(label=d.nature.name, data=aux))

        per_year_data = PerNatureByYear.objects.filter(institution=institution).filter(nature=d.nature)
        per_year_data = per_year_data.filter(year__gte=start_year)
        per_year_data = per_year_data.filter(year__lte=end_year)
        for item in per_year_data:
            cummulative = cummulative + float(item.expensed)
            aux.append([int(date(item.year, 1, 1).strftime("%s000")), cummulative])

    # mbm_years = list of years (3, right now - 2011, 2012, 2013) with 12 months inside
    # each month in turn carries a dict with month name and value or null.
    def nature_is_empty(years):
        for year in years:
            for month in year['data']:
                if month['data'] != 'null' and month['data'] > 0.0001:
                    return False
        return True

    natures_mbm = []
    for nature in ExpenseNature.objects.all():
        mbm_years = []
        expensed_by_month = PerNatureByMonth.objects.filter(institution=institution)
        expensed_by_month = expensed_by_month.filter(nature=nature)

        if legislature:
            all_years = range(start_year, end_year + 1)
        else:
            all_years = [d.year for d in expensed_by_month.dates('date', 'year')]
            all_years = ensure_years_in_range(date_ranges, all_years)

        for year in all_years:
            mbm_series = []
            for month in range(1, 13):
                month_date = date(year, month, 1)

                mname = month_date.strftime("%b")
                try:
                    item = expensed_by_month.get(date=month_date)
                    expensed = float(item.expensed)
                except PerNatureByMonth.DoesNotExist:
                    expensed = 'null'

                mbm_series.append(dict(month=mname, data=str(expensed)))
            mbm_years.append(dict(label=year, data=mbm_series))

        if not nature_is_empty(mbm_years):
            natures_mbm.append(dict(name=nature.name, data=mbm_years))

    c = {'data': data, 'years_data': time_series, 'natures_mbm': natures_mbm,
         'colors': generate_colors(len(data), 0.93, 0.8)}

    c.update(date_ranges)

    return new_render(request, filter_spec, 'per_nature.html', c)


def show_per_legislator(request, filter_spec, export_format=''):

    institution, legislature = parse_filter(filter_spec)
    data = PerLegislator.objects.filter(institution=institution, legislature=legislature).order_by('-expensed')

    if export_format:
        data = data.values(
            'institution__siglum',
            'legislature__date_start',
            'legislature__date_end',
            'legislator__name',
            'legislator__mandate__party__siglum',
            'expensed',
        )
        field_header_map = {
            'institution__siglum': u'Instituição',
            'legislature__date_start': u'Início da legislatura',
            'legislature__date_end': u'Fim da legislatura',
            'legislator__name': u'Parlamentar',
            'legislator__mandate__party__siglum': u'Partido',
            'expensed': u'Valor',
        }
        return _export_csv(request, data, field_header_map)

    date_ranges = get_date_ranges_from_data(institution, data, consolidated_data=True)

    # We may have several mandates for a legislator, potentially with different parties.
    # We only want to show one line per legislator, though, so sum the expenses and list
    # all parties in the party column.
    data_list = []
    for item in data:
        mandates = item.legislator.mandate_set.order_by('date_start')
        legislator_data = dict(legislator=item.legislator,
                               mandates=mandates,
                               expensed=item.expensed)
        data_list.append(legislator_data)
    data = data_list

    c = {'data': data}

    c.update(date_ranges)

    return new_render(request, filter_spec, 'per_legislator.html', c)


def show_legislator_detail(request, filter_spec, legislator_id):

    data, date_ranges = get_basic_objects_for_model(filter_spec)

    try:
        legislator = Legislator.objects.get(pk=legislator_id)

montanha/templates/biggest_suppliers_table.html
<table id="biggest-suppliers-data-table" class="table table-bordered table-striped">
    <thead>
        <tr>
            {% for col in columns %}
                <th>{{ col }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

montanha/templates/footer.html
{% load staticfiles %}

<footer>
    <div class="container">
        <div class="row">
            <div class="span3">
                <h3>Links</h3>
                <ul class="content-menu">
                    <li id="menu-what-is-expenses"><a href="{% url 'montanha:what-is-expenses' %}">O que é verba indenizatória?</a></li>
                    <li id="menu-api"><a href="{{ request.build_absolute_uri }}api/v0/">API Olho Neles</a></li>
                    <li id="menu-contact-us"><a href="{% url 'montanha:contact-us' %}">Fale Conosco</a></li>
                </ul>
            </div>
            <div class="span5">
                {% include 'sourcecode.html' %}
            </div>
            <div class="span4">
                {% include 'creativecommons.html' %}
            </div>
        </div>
    </div>
</footer>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/datatables-bootstrap-pagination.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery-deserialize/jquery.deserialize.js' %}"></script>

<script type="text/javascript" src="{% static "share42/share42.js" %}"></script>

<script type="text/javascript">
// Properly align the form elements.
$.extend($.fn.dataTableExt.oStdClasses, {
    "sWrapper": "dataTables_wrapper form-inline"
});

$(document).ready(function() {
    if (location.hash.substr(0,2) == "#!") {
        $("a[href='#" + location.hash.substr(2) + "']").tab("show");
    }

    $('a[data-toggle="tab"]').on('shown', function (e) {
        var hash = $(e.target).attr('href');
        if (hash.substr(0,1) == "#") {
            location.replace("#!" + hash.substr(1));
        }
    });
});
</script>

montanha/templates/institution.html
{% extends "content.html" %}
{% load staticfiles %}
{% load montanhatags %}

{% block title %}{{ filter_spec|default:'' }} Legislatura{% endblock %}

{% block content %}

<div class="row olhoneles_jumbotron">
    <div class="row text-center">
        <div class="span12">
            <img src="{% static img %}"/>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <div class="destaque">Você quer ver todos os dados ou de alguma legislatura específica?</div>
        </div>
    </div>
    <div class="row text-center">
        <div class="span12">
            <a href="/{{ institution.siglum }}{% url 'montanha:per-nature' %}">
                <button class="btn btn-large">
                    Todos os dados disponíveis.
                </button>
            </a>
        </div>
    </div>
    {% for legislature in legislatures %}
    <div class="row text-center">
        <div class="span12">
            <a href="/{{ institution.siglum }}:{{ legislature.date_start.year }}{% url 'montanha:per-nature' %}">
                <button class="btn btn-large">
                    Legislatura de {{ legislature.date_start.year }}-{{ legislature.date_end.year }}
                </button>
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

{% block footer-extra %}

{% endblock %}

montanha/templates/per_legislator.html
{% extends "base.html" %}
{% load staticfiles %}
{% load montanhatags %}
{% load thumbnail %}

{% block title %} {{ filter_spec|default:'' }} Por Parlamentar {% endblock %}

{% block content %}


    <div class="row">
        <div class="span12">{% share "Por Parlamentar" %}</div>
    </div>
    <div class="row">
        <div class="span12">
            {% csv_link filter_spec 'montanha:per-legislator' %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Parlamentar</th>
                        <th>Partido</th>
                        <th>Valor ressarcido</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in data %}
                    <tr>
                        <td>
                          <a href="{% if filter_spec %}/{{ filter_spec }}{% endif %}{% url 'montanha:show-legislator-detail' d.legislator.id %}">
                            {{ d.legislator.name }}
                          </a>
                        </td>
                        <td>
                            {% for m in d.mandates %}
                                {% if forloop.counter0 %}
                                    /
                                {% endif %}
                                {% if m.party.logo %}<img src="{{ m.party.logo|thumbnail_url:'mini' }}" title="{{ m.party.name }}" alt="{{ m.party.name }}">{% endif %}
                                {% if m.party.siglum %} {{ m.party.siglum }} {% else %} Partido não informado {% endif %} ({{ m.date_start.year }}{% if m.date_end.year %} - {{ m.date_end.year }}{% endif %})
                            {% endfor %}
                        </td>
                        <td>{{ d.expensed|format_currency }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}


{% block footer-extra %}

<script type="text/javascript">
$(document).ready(function(){

    $('#menu-per-legislator').addClass('active').siblings().removeClass('active');
});
</script>

{% endblock %}

montanha/templates/supplier_overview.html
{% extends "content.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load montanhatags %}
{% load bootstrap_toolkit %}

{% block title %}{{ filter_spec|default:'' }} {{ supplier.name }} ({{ supplier.identifier_with_mask }}){% endblock %}

{% block content %}

    <div class="row">
        <div class="span12">
            <h1>{% share supplier.name %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            {% if total_expensed %}
            <table class="alert alert-success table-condensed">
                <tr>
                    <th class="pull-right">Total recebido:</th><td><strong>{{ total_expensed|format_currency }}</strong></td>
                </tr>
            </table>
            {% endif %}
            <table class="alert alert-info table-condensed">
                <tr>
                    <th class="pull-right">CNPJ:</th>
                    <td>{{ supplier.identifier_with_mask }}</td>
                </tr>
                {% if supplier.trade_name %}
                <tr>
                    <th class="pull-right">Nome fantasia:</th>
                    <td>{{ supplier.trade_name }}</td>
                </tr>
                {% endif %}
                {% if supplier.enterprise_type %}
                <tr>
                    <th class="pull-right">Tipo:</th>
                    <td>{{ supplier.enterprise_type }}</td>
                </tr>
                {% endif %}
                {% if supplier.main_activity %}
                <tr>
                    <th class="pull-right">Atividade Principal:</th>
                    <td>{{ supplier.main_activity }}</td>
                </tr>
                {% endif %}
                {% if supplier.secondary_activities.all %}
                <tr>
                    <th class="pull-right">Atividades secundárias:</th>
                    <td>{% for x in supplier.secondary_activities.all %}{{ x.name }}.{% if not forloop.last %}<br/>{% endif %}{% endfor %}</td>
                </tr>
                {% endif %}

                {% if supplier.address %}
                <tr>
                    <th class="pull-right">Endereço:</th>
                    <td>{{ supplier.address }}, {{ supplier.address_number }}, {% if supplier.address_complement %}{{ supplier.address_complement }},{% endif %} {% if supplier.neighborhood %}{{ supplier.neighborhood }},{% endif %} {% if supplier.city %}{{ supplier.city }}/{% endif %}{{ supplier.state }}</td>
                </tr>
                {% endif %}
                {% if supplier.postal_code %}
                <tr>
                    <th class="pull-right">CEP:</th>
                    <td>{{ supplier.postal_code }}</td>
                </tr>
                {% endif %}
                {% if supplier.phone %}
                <tr>
                    <th class="pull-right">Telefone:</th>
                    <td>{{ supplier.phone }}</td>
                </tr>
                {% endif %}
                {% if supplier.email %}
                <tr>
                    <th class="pull-right">Email:</th>
                    <td>{{ supplier.email }}</td>
                </tr>
                {% endif %}
                {% if supplier.date_opened %}
                <tr>
                    <th class="pull-right">Data de abertura:</th>
                    <td>{{ supplier.date_opened|date:"d/m/Y" }}</td>
                </tr>
                {% endif %}
                {% if supplier.situation.name %}
                <tr>
                    <th class="pull-right">Situação:</th>
                    <td>{{ supplier.situation.name }}</td>
                </tr>
                {% endif %}
                {% if supplier.situation_date %}
                <tr>
                    <th class="pull-right">Situação data:</th>
                    <td>{{ supplier.situation_date|date:"d/m/Y" }}</td>
                </tr>
                {% endif %}
                {% if supplier.situation_reason %}
                <tr>
                    <th class="pull-right">Motivo situação:</th>
                    <td>{{ supplier.situation_reason }}</td>
                </tr>
                {% endif %}
                {% if supplier.last_update %}
                <tr>
                    <th class="pull-right">Última atualização:</th>
                    <td>{{ supplier.last_update|date:"d/m/Y"}}</td>
                </tr>
                {% endif %}
                {% if supplier.juridical_nature %}
                <tr>
                    <th class="pull-right">Natureza jurídica:</th>
                    <td>{{ supplier.juridical_nature }}</td>
                </tr>
                {% endif %}
            </table>       </div>
    </div>
    <div class="row">
        <div class="span12">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#houses" data-toggle="tab"><i class="icon-list-alt"></i> Por casa legislativa</a></li>
                <li><a href="#top-buyers" data-toggle="tab"><i class="icon-list-alt"></i> Maiores compradores</a></li>
                <li><a href="#all-expenses" data-toggle="tab"><i class="icon-list-alt"></i> Todos os gastos</a></li>
            </ul>
            <div class="tab-content" id="tab-detail-supplier">
                <div id="houses" class="tab-pane active">
                    <table class="span6 table table-bordered table-striped">
                        <thead>
                            <th>Casa parlamentar</th>
                            <th>Valor</th>
                        </thead>
                        <tbody>
                            {% for h in house_data %}
                            <tr>
                                <td>
                                    <a href="/{{ h.siglum }}{% url 'montanha:show-supplier-detail' supplier.id %}">
                                        <img src="{{ h.logo|thumbnail_url:'mini' }}">
                                        {{ h.name }} ({{ h.siglum }})
                                    </a>
                                </td>
                                <td>{{ h.expensed|format_currency }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div id="houses-placeholder" style="height:300px" class="span5"></div>
                </div>
                <div id="all-expenses" class="tab-pane">
                    {% expenses_table "Tipo de gasto" "Parlamentar (Partido)" "Número do Documento" "Data" "Valor" %}
                </div>
                <div id="top-buyers" class="tab-pane">
                    <div class="span4">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Parlamentar (Partido)</th>
                                    <th>Valor</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for d in top_buyers %}
                                <tr>
                                    <td>
                                        <a href="{% if filter_spec %}/{{ filter_spec }}{% else %}/{{ d.mandate__legislature__institution__siglum }}{% endif %}{% url 'montanha:show-legislator-detail' d.mandate__legislator__id %}">
                                        {{ d.mandate__legislator__name }} ({{ d.mandate__party__siglum }})
                                        </a>
                                    </td>
                                    <td>{{ d.expensed|format_currency }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="span6">
                        <div id="placeholder" class="span6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block footer-extra %}

{% include 'per_party_graph.html' %}

<script>
$(document).ready(function(){

	var house_data = [
        {% for h in house_data %}{label: "{{ h.siglum }}", color: "{{ colors|itercycle:forloop.counter0 }}", data: {{ h.expensed }}},{% endfor %}
    ]

    plot_houses_graph = function() {
        $.plot('#houses-placeholder', house_data, {
            series: {
                pie: {
                    show: true,
                }
            },
        });
    }

});
</script>
{% expenses_data_table 'supplier_all' 'ttttm' supplier.id %}

<script type="text/javascript">
$(document).ready(function(){
    $('#menu-per-supplier').addClass('active').siblings().removeClass('active');

    plot_houses_graph();

    $('a[href="#top-buyers"]').on('shown', function() {
        plot_per_party_graph();
    });

});
</script>

{% endblock %}